version: "3"
services:
  bot:
    build: .
    env_file:
      - .env
    volumes:
      - .:/code
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    volumes:
      - ./database:/data/db
